version: '3.8'

services:
  redis_master1:
    image: redis:7.0.12
    container_name: redis_master1
    ports:
      - 6300:6300
      - 16300:16300
    volumes:
      - ./redis-cluster/master1/data:/data
      - ./redis-cluster/master1/redis_master_6300.conf:/usr/local/etc/redis/redis_master_6300.conf
    restart: always
    networks:
      - redis_cluster
    command: redis-server /usr/local/etc/redis/redis_master_6300.conf

  redis_master2:
    image: redis:7.0.12
    container_name: redis_master2
    ports:
      - 6301:6301
      - 16301:16301
    volumes:
      - ./redis-cluster/master2/data:/data
      - ./redis-cluster/master2/redis_master_6301.conf:/usr/local/etc/redis/redis_master_6301.conf
    restart: always
    networks:
      - redis_cluster
    depends_on:
      - redis_master1
    command: redis-server /usr/local/etc/redis/redis_master_6301.conf

  redis_master3:
    image: redis:7.0.12
    container_name: redis_master3
    ports:
      - 6302:6302
      - 16302:16302
    volumes:
      - ./redis-cluster/master3/data:/data
      - ./redis-cluster/master3/redis_master_6302.conf:/usr/local/etc/redis/redis_master_6302.conf
    restart: always
    networks:
      - redis_cluster
    depends_on:
      - redis_master2
    command: redis-server /usr/local/etc/redis/redis_master_6302.conf

  redis_replica1:
    image: redis:7.0.12
    container_name: redis_replica1
    ports:
      - 6400:6400
      - 16400:16400
    volumes:
      - ./redis-cluster/replica1/data:/data
      - ./redis-cluster/replica1/redis_replica_6400.conf:/usr/local/etc/redis/redis_replica_6400.conf
    restart: always
    networks:
      - redis_cluster
    depends_on:
      - redis_master3
    command: redis-server /usr/local/etc/redis/redis_replica_6400.conf

  redis_replica2:
    image: redis:7.0.12
    container_name: redis_replica2
    ports:
      - 6401:6401
      - 16401:16401
    volumes:
      - ./redis-cluster/replica2/data:/data
      - ./redis-cluster/replica2/redis_replica_6401.conf:/usr/local/etc/redis/redis_replica_6401.conf
    restart: always
    networks:
      - redis_cluster
    depends_on:
      - redis_replica1
    command: redis-server /usr/local/etc/redis/redis_replica_6401.conf

  redis_replica3:
    image: redis:7.0.12
    container_name: redis_replica3
    ports:
      - 6402:6402
      - 16402:16402
    volumes:
      - ./redis-cluster/replica3/data:/data
      - ./redis-cluster/replica3/redis_replica_6402.conf:/usr/local/etc/redis/redis_replica_6402.conf
    restart: always
    networks:
      - redis_cluster
    depends_on:
      - redis_replica2
    command: redis-server /usr/local/etc/redis/redis_replica_6402.conf

  redis_cluster_init:
    image: redis:7.0.12
    container_name: redis_cluster_init
    volumes:
      - ./redis-cluster/init-redis-cluster.sh:/init-redis-cluster.sh
    networks:
      - redis_cluster
    depends_on:
      - redis_master1
      - redis_master2
      - redis_master3
      - redis_replica1
      - redis_replica2
      - redis_replica3
    entrypoint: ['/bin/bash', '/init-redis-cluster.sh']

networks:
  redis_cluster:
    external: false
    driver: host
